name = "ilearning-database"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "LearningDB"
database_name = "ilearning-database"
database_id = "ba29fe5f-e1e3-4bf1-86b9-b2959489e6c4"
preview_database_id = "LearningDB"